config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :foods
  resources :recipes do
    resources :recipe_foods
  end
  resources :shoppinglists
  resources :public_recipes
  post 'toggle_public', to: 'recipes#toggle'
  root "foods#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods, dependent: :destroy
  belongs_to :user
  validates :name, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods, dependent: :destroy
  belongs_to :user
  validates :name, presence: true
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :foods, dependent: :destroy
  has_many :recipes, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_user, expect: [:update]
  def index
    @user = current_user
    @foods = @user.foods.includes(:user)
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user = current_user
    if @food.save
      redirect_to foods_path(current_user)
    else
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    if @food.destroy
      flash[:notice] = 'Food deleted successfully!'
    else
      flash.now[:alert] = @food.errors.full_messages.first if @food.errors.any?
      render :index, status: 400
    end
    redirect_to foods_path(current_user)
  end

  private

  def food_params
    params.require(:food).permit(:name, :quantity, :price, :measurement_unit)
  end

  def set_user
    @user = current_user
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  before_action :set_user
  def index
    @public_recipes = Recipe.includes(recipe_foods: :food).where(public: true)
  end

  private

  def set_user
    @user = current_user
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :find_recipe, :find_user
  before_action :find_recipe_food, only: %i[edit update destroy]

  def new
    @foods = current_user.foods
    if (@recipe.user = current_user)
      @recipe_food = RecipeFood.new
    else
      flash[:alert] = 'You cannot access an ingredient on a recipe that belongs to other Users.'
      redirect_to recipes_path
    end
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe_food.recipe = @recipe

    if @recipe_food.save
      redirect_to recipe_path(@recipe), notice: 'New ingredient was successfully added.'
    else
      flash[:alert] = @recipe_food.errors.full_messages.first if @recipe_food.errors.any?
      redirect_to recipes_path
    end
  end

  def edit
    @foods = current_user.foods
  end

  def update
    if @recipe_food.update(recipe_food_params)
      redirect_to recipe_path(@recipe), notice: 'Ingredient was successfully updated.'
    else
      flash[:alert] = @recipe_food.errors.full_messages.first if @recipe_food.errors.any?
      render :edit, status: 400
    end
  end

  def destroy
    unless @recipe_food.recipe.user == current_user
      flash[:alert] = 'You cannot delete the ingredient belongs to other Users.'
      return redirect_to recipe_path(@recipe)
    end

    if @recipe_food.destroy
      flash[:notice] = 'Ingredient deleted successfully removed.'
    elsif @recipe_food.errors.any?
      flash[:alert] = @recipe_food.errors.full_messages.first
    end
    redirect_to recipe_path(@recipe)
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end

  def find_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end

  def find_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  def find_user
    @user = current_user
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_user, expect: [:update]
  # def index
  #   @users = User.includes(recipes: %i[recipe_foods foods]).includes(:foods)
  #   @food_counts = @users.map { |user| [user.name, user.foods.count] }
  #   @food_prices = @users.map { |user| [user.name, user.foods.sum(:price)] }
  #   @recipes = Recipe.includes(:recipe_foods, :foods).where(public: true).order('created_at DESC')
  # end
  def index
    @recipes = @user.recipes
  end

  # def show
  #   @recipe = Recipe.find(params[:id])
  #   @recipe_foods = @recipe.recipe_foods
  # end

  def new
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.includes(:foods).find(params[:id])
    @recipe_foods = @recipe.recipe_foods
  end

  def public_allocation
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: params[:recipe][:public])
    redirect_to @recipe
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = @user

    if @recipe.save
      flash[:notice] = 'Recipe created successfully!'
      redirect_to recipe_path(id: @recipe.id)
    else
      flash.now[:alert] = @recipe.errors.full_messages.first if @recipe.errors.any?
      render :new, status: unprocessable_entity
    end
  end

  # def destroy_from_form
  #   @food = Food.find(params[:food_id])
  #   @food.destroy
  #   redirect_to foods_path(current_user)
  # end
  def destroy
    @recipe = Recipe.find(params[:id])

    if @recipe.destroy
      flash[:notice] = 'Recipe deleted successfully!'
      redirect_to recipes_path
    else
      flash.now[:alert] = @recipe.errors.full_messages.first if @recipe.errors.any?
      render :index, status: 400
    end
  end

  def toggle
    @recipe = Recipe.find(params[:id])
    @recipe.public = !@recipe.public
    text = @recipe.public? ? 'public' : 'private'

    if @recipe.save
      flash[:notice] = "#{@recipe.name} is now #{text}!"
    elsif @recipe.errors.any?
      flash[:alert] = @recipe.errors.full_messages.first
    end
    redirect_to recipe_path(id: @recipe.id)
  end

  private

  def set_user
    @user = current_user
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/shoppinglists_controller.rb
class ShoppinglistsController < ApplicationController
  before_action :find_user

  def index
    @user = current_user
    @food = @user.foods.left_outer_joins(:recipe_foods).where(recipe_foods: { id: nil }).includes(:recipe_foods)
    @food_counts = @food.count
    @food_prices = @food.sum(:price)
  end

  private

  def find_user
    @user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/index.html.erb
<%= stylesheet_link_tag "food", "data-turbo-track": "reload" %>
<section class="food-section">
<%= link_to 'New Food', new_food_path(), class: 'add-button button' %>
<div class="food-container">
  <table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Measurement Unit</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @user.foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.quantity %></td>
        <td><%= food.price %></td>
        <td><%= food.measurement_unit %></td>
        <td><%= link_to 'Delete', food_path(food), data: { turbo_method: :delete }, class: 'delete-btn' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</section>

app/views/foods/new.html.erb
<h1>New Food</h1>
<%= form_for @food do |f| %>
  <div class="form-element">
    <%= f.label :name %>
    <%= f.text_field :name, required: true %>
  </div>
  <div class="form-element">
    <%= f.label :quantity %>
    <%= f.number_field :quantity %>
  </div>
  <div class="form-element">
    <%= f.label :price %>
    <%= f.number_field :price, required: true %>
  </div>
  <div class="form-element">
    <%= f.label :measurement_unit %>
    <%= f.text_field :measurement_unit, required: true %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorRecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="<%= user_signed_in? ? '' : 'mainbg' %>">
      <% if user_signed_in? %>
      <div><%= render partial: "shared/menu" %></div>   
      <% end %>
      <div class="main"><%= yield %></div> 
  </body>
</html>
 

app/views/public_recipes/index.html.erb
<%= stylesheet_link_tag "shop", "data-turbo-track": "reload" %>
<section class="recipe-public">
  <h1 class="text-center">Public Recipes</h1>
<% @public_recipes.includes(recipe_foods: :food).each do |public_recipe| %>
  <%= link_to recipe_path(id: public_recipe.id), class: "text-decoration-none text-dark" do%>
  <div class="card my-3">
    <div class="card-body">
      <div class="sub-public">
        <div class="public-details">
          <p class="card-title"><%= public_recipe.name %></p>
          <p class="card-subtitle mb-2 text-muted">By: <%= public_recipe.user.name.capitalize %></p>
        </div>
        <div>
          <p class="card-text"><b>Total food items:</b> <%= public_recipe.recipe_foods.size %></p>
          <p class="card-text"><b>Total Price: $</b>
            <% total_price = 0 %>
            <% public_recipe.recipe_foods.each do |recipe_food| %>
            <% total_price += recipe_food.quantity ||= 0 * recipe_food.food.price ||= 0 %>
            <% end %>
            <%= total_price %>
          </p>
        </div>
      </div>
    </div>
  </div>
<% end %>
<% end %>
</section>

app/views/recipe_foods/_ingredients_edit_form.html.erb
<%= form_with model: recipe_food, url: url, class: "my-3" do |f| %>
  <div class="mb-3">
    <%= f.label :quantity, "Quantity", style: "display: block" %>
    <%= f.number_field :quantity, placeholder: 0 %>
  </div>

  <div class="mb-3">
    <%= f.label :food_id, "Food", style: "display: block" %>
    <%= f.collection_select(:food_id, foods, :id, :name) %>
  </div>

  <%= f.submit "Update ingredients", class: "create-btn btn" %>
<% end %>

app/views/recipe_foods/_ingredients_new_form.html.erb
<%= form_with model: recipe_food, url: url, class: "my-3" do |f| %>
  <div class="mb-3">
    <%= f.label :quantity, "Quantity", style: "display: block" %>
    <%= f.number_field :quantity, placeholder: 0 %>
  </div>

  <div class="mb-3">
    <%= f.label :food_id, "Food", style: "display: block" %>
    <%= f.collection_select(:food_id, foods, :id, :name) %>
  </div>

  <%= f.submit "Add ingredients", class: "create-btn btn" %>
<% end %>

app/views/recipe_foods/edit.html.erb
<h1>Update Ingredient</h1>

<% if (@foods.empty?) %>
  <h2>You have not added any food yet. please add some foods</h2>
<% else %>
<%= render "ingredients_edit_form", recipe_food: @recipe_food, foods: @foods, url: recipe_recipe_food_path(recipe_id: @recipe.id, id: @recipe_food.id) %>
<% end %>

<button><%= link_to "Add food", new_food_path %></button>

app/views/recipe_foods/index.html.erb
<%= stylesheet_link_tag "shop", "data-turbo-track": "reload" %>
<section>
  <h1>Shopping List</h1>
  <div class="shop-container">
    <div class="shop-hero">
      <p>Amount of food item to buy: <%= @food_counts %></p>
      <p>Total value of food needed: $ <%= @food_prices %></p>
    </div>
    <table>
      <thead>
        <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        <% @food.each do |food| %>
          <tr>
            <td><%= food.name %></td>
            <td><%= food.quantity %></td>
            <td><%= food.price %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</section>

app/views/recipe_foods/new.html.erb
<div class="d-flex justify-content-center">
  <div>
    <h1 class="text-primary">Add Ingredient</h1>
  
    <% if (@foods.empty?) %>
      <h2>You have not added any food yet. please add some foods</h2>
    <% else %>
      <%= render "ingredients_new_form", recipe_food: @recipe_food, foods: @foods, url: recipe_recipe_foods_path%>
    <% end %>
    
    <br>
    
    <%= link_to(request.referer || root_path, class: "btn btn-warning") do %>
      <%= content_tag :i, nil, class: "bi bi-arrow-left-circle" %>
      Go back
    <% end %>
  </div>
</div>

app/views/recipes/index.html.erb
<%= stylesheet_link_tag "recipe", "data-turbo-track": "reload" %>
<section class="recipe-section">
<h1>All recipes</h1>
<div class="recipe-container">
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><%= recipe.description %></td>
        <td><%= link_to 'View', recipe_path(id: recipe.id), class: 'preview-btn' %></td>
        <td><%= link_to 'Delete', recipe_path(id: recipe.id), data: { turbo_method: :delete, turbo_confirm: 'Delete the recipe?' }, class: 'delete-btn' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div><button type="button" class="btn"><%= link_to "Add a new recipe", new_recipe_path %></button>
<button type="button" class="btn"><%= link_to "Go to public recipes", public_recipes_path %></button>
</div>

</section>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<section>
  <%= form_with model: @recipe, url: recipes_path, local: true do |f| %>
    <%= f.label :name, 'Recipe name' %>
    <%= f.text_field :name, autofocus: true, placeholder: 'Add recipe name' %><br/>

    <%= f.label :preparation_time, 'Preparation Time'%>
    <%= f.number_field :preparation_time, autofocus: true, placeholder: 'Time in hours' %><br/>

    <%= f.label :cooking_time, 'Cooking Time' %>
    <%= f.number_field :cooking_time, autofocus: true, placeholder: 'Time in hours' %><br/>

    <%= f.label :description, 'Description' %>
    <%= f.text_area :description, autofocus: true, placeholder: 'Recipe description' %><br/>

    <%= f.label :public, "Do you want to make it public?" %>
    <%= f.check_box :public, autofocus: true%><br/>

    <%= f.submit "Create recipe", class: "create-btn btn" %>
  <% end %>

</section>

<p><%=link_to 'Back', recipes_path %></p>

app/views/recipes/show.html.erb
<%= stylesheet_link_tag "recipe", "data-turbo-track": "reload" %>
<section class="recipe-show">
<h1><%= @recipe.name %></h1>
    <div class="food-container">
        <div class="food-name">
            <p>Preparation time:<%= @recipe.preparation_time  %>hours</p>
            <p>Cooking time: <%= @recipe.cooking_time %></p>
            <p>Description: <%= @recipe.description%></p>  
        </div>
<%= form_for @recipe, url: toggle_public_path(id: @recipe.id), method: :post do |f| %>
  <div class="swith-btn">
    <p><%= @recipe.public? ? 'Public' : 'Private' %></p>
    <label class="switch">
    <div><%= f.submit "" %></div>
      <%= f.check_box :public, { checked: @recipe.public } %>
      <span class="slider round"></span>
    </label>
  </div>
  
<% end %>

    </div>
    <div class="recipe-btns">
        <%= link_to 'Generate Shopping List', shoppinglists_path(), class: 'button' %>
        <%= link_to 'Add ingredient', new_recipe_recipe_food_path(recipe_id: @recipe.id), class: 'button' %>
    </div>
    <table>
  <thead>
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Value</th>
      <th class="action">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @recipe_foods.includes(:food).each do |recipe_food| %>
      <tr>
        <td><%= recipe_food.food.name %></td>
        <td><%= recipe_food.quantity %> <%= recipe_food.food.measurement_unit%></td>
        <td>$ <%= recipe_food.food.price %></td>
        <td>
            <%= link_to 'Delete', recipe_recipe_food_path(recipe_id: @recipe.id, id: recipe_food.id), data: { turbo_method: :delete }, class: 'delete-btn' %>
            <%= link_to 'Modify', edit_recipe_recipe_food_path(recipe_id: @recipe.id, id: recipe_food.id), class: ' delete-btn modify-btn' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</section>

app/views/shared/_menu.html.erb
<%= stylesheet_link_tag "menu", "data-turbo-track": "reload" %>
<nav class="navbar" >
  <div class="container">
    <a class="navbar-brand" href="/">RECIPE APP</a>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="/">Foods</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/recipes">Recipes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/public_recipes">Public</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/shoppinglists">ShoppingList</a>
        </li>
      </ul>
      <span class="navbar-text">
        <%= button_to("Log Out", destroy_user_session_path, method: :delete, class: "btn btn-danger") %>
      </span>
    </div>
  </div>
</nav>

app/views/shoppinglists/index.html.erb
<%= stylesheet_link_tag "shop", "data-turbo-track": "reload" %>
<section>
  <h1>Shopping List</h1>
  <div class="shop-container">
    <div class="shop-hero">
      <p>Amount of food item to buy: <%= @food_counts %></p>
      <p>Total value of food needed: $ <%= @food_prices %></p>
    </div>
    <table>
      <thead>
        <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        <% @food.each do |food| %>
          <tr>
            <td><%= food.name %></td>
            <td><%= food.quantity %></td>
            <td><%= food.price %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</section>